apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "whisper-ui.fullname" . }}-prometheus-viewer
  labels:
    {{- include "whisper-ui.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "whisper-ui.fullname" . }}-prometheus-viewer
subjects:
- kind: ServiceAccount
  name: whisper-ui
  namespace: {{ include "whisper-ui.namespace" . }}
