apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-tournament-db
  namespace: {{ include "whisper-ui.namespace" . }}
  labels:
    {{- include "whisper-ui.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tournament.storage | default "1Gi" }}
