apiVersion: v1
kind: Secret
metadata:
  name: whisper-tournament-secret
  namespace: {{ include "whisper-ui.namespace" . }}
  labels:
    {{- include "whisper-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  TOURNAMENT_SECRET: {{ .Values.tournament.secret | default (randAlphaNum 32) | quote }}
  ADMIN_TOKEN: {{ .Values.tournament.adminToken | default (randAlphaNum 32) | quote }}
