apiVersion: v1
kind: Service
metadata:
  name: whisper-ui
  namespace: {{ include "whisper-ui.namespace" . }}
  labels:
    {{- include "whisper-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    {{- include "whisper-ui.selectorLabels" . | nindent 4 }}
